name: PR Notification to Discord
on: push

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Format Commit Messages
        run: |
          COMMIT_MESSAGES=$(jq -r '[.commits[] | "- " + .message] | join("\n")' <<< '${{ toJson(github.event.commits) }}')

          PAYLOAD=$(jq -n --arg ref "${{ github.ref }}" \
                          --arg pusher "${{ github.event.pusher.name }}" \
                          --arg compare "${{ github.event.compare }}" \
                          --arg commits "$COMMIT_MESSAGES" \
                          '{"content": "**New Push Event!** 🚀\n**Branch:** \($ref)\n**By:** \($pusher)\n🔗 **Compare:** \($compare)\n\n🔄 **Commits:**\n\($commits)"}')

          curl -H "Content-Type: application/json" -X POST \
          -d "$PAYLOAD" \
          "https://discord.com/api/webhooks/1348409326573977760/I6vRzZxUh5nK7QDI9ZcGBKLfnhCidew9suc4j5iO45IwEytN9tXK0U2Tl9W44-wjJRED"
