name: PR Notification to Discord
on:
  pull_request:
    types: [opened]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send PR notification to Discord
        run: |
          curl -H "Content-Type: application/json" -X POST \
          -d '{"content": "**New PR Opened!** 🚀\nTitle: ${{ github.event.pull_request.title }}\nBy: ${{ github.event.pull_request.user.login }}\n🔗 [View PR](${{ github.event.pull_request.html_url }})"}' \
          "https://discord.com/api/webhooks/1348409326573977760/I6vRzZxUh5nK7QDI9ZcGBKLfnhCidew9suc4j5iO45IwEytN9tXK0U2Tl9W44-wjJRED"

